### ISSUE TITLE
can not use after upgrade

### ISSUE THREAD

**Issue by lolieatapple** [Nutlope/aicommits#129] opened 2023-03-05 13:30 UTC
### Bug description

┌   aicommits
│
◇  Detected 1 staged file:
     contracts/GameCore.sol
│
◑  The AI is analyzing your changes
│
└  ✖ read ECONNRESET

    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)

    aicommits v1.3.0

    Please open a Bug report with the information above:
    https://github.com/Nutlope/aicommits/issues/new/choose

### aicommits version

v1.3.0

### Environment

```shell
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 163.20 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 9.2.0 - /opt/homebrew/bin/npm
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment] 2023-03-05 22:25
Does this happen consistently for you?

I wonder if all we need is an error handling to ignore the error:
https://stackoverflow.com/questions/53912439/nodejs-econnreset

Please try using the [latest Node v16 (v16.19.1)](https://nodejs.org/download/release/latest-v16.x/).

---

Duplicate of https://github.com/Nutlope/aicommits/issues/125

**Comment by privatenumber** [comment] 2023-03-10 14:21
Can you see if the latest version fixes it for you?

https://github.com/Nutlope/aicommits/releases/latest

**Comment by lolieatapple** [comment] 2023-03-10 15:11
and node v16.19.1 not work, too.
```
  installing : node-v16.19.1
       mkdir : /usr/local/n/versions/node/16.19.1
       fetch : https://nodejs.org/dist/v16.19.1/node-v16.19.1-darwin-arm64.tar.xz
     copying : node/16.19.1
   installed : v16.19.1

node -v
v16.19.1

┌   aicommits
│
◇  Detected 1 staged file:
     README.md
│
◓  The AI is analyzing your changes
│
└  ✖ read ECONNRESET

    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)

    aicommits v1.5.0

    Please open a Bug report with the information above:
    https://github.com/Nutlope/aicommits/issues/new/choose
```

**Comment by privatenumber** [comment] 2023-03-11 02:36
Based on your TLS error, it sounds like your computer may have some SSL configurations.
Are you using a VPN or some special network configuration?

**Comment by privatenumber** [comment] 2023-03-11 02:38
Closing in favor of https://github.com/Nutlope/aicommits/issues/136

Let's take the discussion there

**Closed by privatenumber** 2023-03-11 02:38 UTC
Labels: bug, pending triage
