### ISSUE TITLE
adding commit prefixes and emojis 

### ISSUE THREAD

**Issue by mhkarimi1383** [Nutlope/aicommits#115] opened 2023-02-24 22:24 UTC
Hi,

I used to add some common prefixes to my commit messages (like fix, feat, doc, etc.) also they have some emojis that I will always add them to the beginning of the messages..

**Comment by privatenumber** [comment] 2023-03-04 03:34
Closing as a duplicate of https://github.com/Nutlope/aicommits/issues/111

**Closed by privatenumber** 2023-03-04 03:34 UTC
Labels: feature
