### ISSUE TITLE
 Du[n] is not a function

### ISSUE THREAD

**Issue by chenzheio** [Nutlope/aicommits#144] opened 2023-03-09 17:31 UTC
### Bug description

┌   aicommits 
│
◇  Detected 2 staged files:
     .env
     .gitignore
│
└  ✖ Du[n] is not a function

    at he (file:///Users/zhe/.config/yarn/global/node_modules/aicommits/dist/cli.mjs:61:2965)
    at async file:///Users/zhe/.config/yarn/global/node_modules/aicommits/dist/cli.mjs:64:15

    aicommits v1.3.0

### aicommits version

v1.3.0

### Environment

```shell
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 198.95 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.2 - /opt/homebrew/opt/node@18/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.0 - /opt/homebrew/opt/node@18/bin/npm
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment] 2023-03-09 22:52
Duplicate of https://github.com/Nutlope/aicommits/issues/126

Did you check your `~/.aicommits` file for invalid properties?

**Closed by privatenumber** 2023-03-09 22:52 UTC
Labels: bug, pending triage

**Comment by chenzheio** [comment] 2023-03-10 11:05
I've add `locale=zh` into `~/.aicommits` then this error is come.
I fetch the `devlop` branch into local, and run npm pack then install the .tgz file the problem resolved.

**Comment by privatenumber** [comment] 2023-03-10 11:10
`loacle=zh` is not released yet. Will release soon!
