### ISSUE TITLE
Adding Signed Commits

### ISSUE THREAD

**Issue by Mahmoudgalalz** [Nutlope/aicommits#85] opened 2023-02-19 21:10 UTC
We should consider the GPG key to use gpg commits, to show if this commits is verified or not

I have implement it, so l will make a PR and make your review if there's smth else I should consider

**Comment by privatenumber** [comment] 2023-02-19 23:18
Closing as duplicate of https://github.com/Nutlope/aicommits/issues/33

**Closed by privatenumber** 2023-02-19 23:18 UTC
