### ISSUE TITLE
Option for Auto Commit without validating the commit message

### ISSUE THREAD

**Issue by yotamcuralife** [Nutlope/aicommits#156] opened 2023-03-15 13:27 UTC
### Feature request

Please add ann option, maybe a flag that will approve the commit automatically without needing to approve it, it will make my workflow much faster.

### Why?

Today every time im making commit i need to approve it, it means 2 more click, one to focus on the terminal and the other to enter the approval. I want to pass that steps.

Its a great opportunity to say I LOVE this Plugin! It needs to be elevated as it is so useful!

**Comment by privatenumber** [comment] 2023-03-16 02:51
Closing as a duplicate of https://github.com/Nutlope/aicommits/issues/61

**Closed by privatenumber** 2023-03-16 02:51 UTC
Labels: feature, pending triage
