### ISSUE TITLE
Bug Issue, Du[n] is not a function

### ISSUE THREAD

**Issue by rrcoder0167** [Nutlope/aicommits#131] opened 2023-03-05 21:05 UTC
### Bug description

I got this bug while running aicommits:

`┌   aicommits 
│
◇  Detected 3 staged files:
     static/orange_ui.js
     static/styles.css
     templates/home.html
│
└  ✖ Du[n] is not a function

    at he (file:///opt/homebrew/lib/node_modules/aicommits/dist/cli.mjs:61:2965)
    at async file:///opt/homebrew/lib/node_modules/aicommits/dist/cli.mjs:64:15

    aicommits v1.3.0`

### aicommits version

1.3.0

### Environment

```shell
System:
    OS: macOS 13.2
    CPU: (8) arm64 Apple M1
    Memory: 99.41 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.6.0 - /opt/homebrew/bin/node
    npm: 9.6.0 - /opt/homebrew/bin/npm
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment] 2023-03-05 22:23
Duplicate of https://github.com/Nutlope/aicommits/issues/126

See solution there

**Closed by privatenumber** 2023-03-05 22:23 UTC
Labels: bug, pending triage
