### ISSUE TITLE
Feature: Add flag for custom prompts to increase user flexibility and language support

### ISSUE THREAD

**Issue by atikahe** [Nutlope/aicommits#103] opened 2023-02-22 10:01 UTC
Advantages of having a flag to allow additional custom prompt:
1. More flexibility for the user in configuring how they want the commit message to look like. Sometimes we want to use the full Conventional style, sometimes only parts of it (e.g. having "Refactor" or "Feature" prefix, etc).
2. Support for other languages without any changes on the program.
3. Save the custom prompt so user don't have to re-type each time.

**Comment by atikahe** [comment] 2023-02-22 10:04
Will be happy to submit a PR if this is useful 🔥

**Comment by privatenumber** [comment] 2023-02-22 11:45
Language request is a duplicate of https://github.com/Nutlope/aicommits/issues/30

Not sure what you mean by custom prompt.

**Comment by law-chain-hot** [comment] 2023-02-28 06:48
> Language request is a duplicate of #30
> 
> Not sure what you mean by custom prompt.

I think that @atikahe means having a flag like `--custom='<custom prompt>'`, in order to customize the output

which will be append to promptTemplate as following, like 
```js
const newPromptTemplate = promptTemplate + `<custom prompt>`
```
Relative Code👇🏻
https://github.com/Nutlope/aicommits/blob/2041aee003aec7453cc204676f2b358c3b020eeb/src/utils/openai.ts#L7

**Comment by privatenumber** [comment] 2023-03-10 23:29
Closing as language support was added here: https://github.com/Nutlope/aicommits/pull/96

I'm not sure about the custom prompt one but feel free to open a separate issue for that with more details.

**Closed by privatenumber** 2023-03-10 23:29 UTC

**Comment by Silidrone** [comment] 2025-02-19 16:35
@privatenumber The OP's inquiry is pretty straightforward and unambigous IMO, @law-chain-hot further clarified what the OP meant. Is there such a feature in aic?
