### ISSUE TITLE
error: read ECONNRESET at TLSWrap.onStreamRead

### ISSUE THREAD

**Issue by moonlitusun** [Nutlope/aicommits#136] opened 2023-03-06 15:25 UTC
### Bug description

Detected 1 staged file:
     "content/post/__1-\346\234\252\346\235\245\345\267\262\346\235\245/2023/diary.md"
│
◓  The AI is analyzing your changes   
│
└  ✖ read ECONNRESET

    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)

    aicommits v1.3.0

    Please open a Bug report with the information above:
    https://github.com/Nutlope/aicommits/issues/new/choose

### aicommits version

1.3.0

### Environment

```shell
OS: macOS 13.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 141.88 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.1 - ~/.volta/tools/image/node/16.19.1/bin/node
    Yarn: 1.22.18 - ~/.volta/tools/image/yarn/4.0.0-rc.39/bin/yarn
    npm: 8.19.3 - ~/.volta/tools/image/node/16.19.1/bin/npm
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment] 2023-03-07 01:41
Does this happen consistently on the same changes or just occasionally?

Will look into implementing retry.

**Comment by moonlitusun** [comment] 2023-03-07 16:02
> 

Every time when i try

**Comment by privatenumber** [comment] 2023-03-10 14:21
Can you see if the latest version fixes it for you?

https://github.com/Nutlope/aicommits/releases/latest

**Comment by privatenumber** [comment] 2023-03-11 02:39
Curious about your network configurations.

Are you using a VPN or some special network configuration?

**Comment by lolieatapple** [comment] 2023-03-11 10:31
Yes, I used an VPN. but it seems the aicommits not go through VPN. 
I tried many time, it only could use when I use a system global VPN.
could you make it works with:
```
export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890
```

**Comment by privatenumber** [comment] 2023-03-12 00:45
Ah gotcha. That makes a lot more sense. Previously, we were using axios behind the scenes, and axios supports those env variables:

> You can also define your proxy using the conventional `http_proxy` and
  // `https_proxy` environment variables. If you are using environment variables
  // for your proxy configuration, you can also define a `no_proxy` environment
  // variable as a comma-separated list of domains that should not be proxied.

**Comment by lolieatapple** [comment] 2023-03-13 14:33
I have tried. use axios@0.27.2 is ok for me, the code modify is below:
<img width="953" alt="image" src="https://user-images.githubusercontent.com/54833180/224732663-595094e6-14fe-4ea0-afcd-8163c3da5069.png">

could you help to update https to axios@0.27.2 ?

**Comment by lolieatapple** [comment] 2023-03-13 14:34
My code may not look very good, but using axios@0.27.2 really solved my problem.

**Comment by privatenumber** [comment] 2023-03-14 00:35
We were using axios before, but removed it to keep the package light:
https://github.com/Nutlope/aicommits/pull/106

**Comment by lolieatapple** [comment] 2023-03-14 02:09
I think usability is more important than being lightweight. Thank you.

**Comment by privatenumber** [comment] 2023-03-14 02:18
You probably missed the PR reference above, but we're getting both: https://github.com/Nutlope/aicommits/pull/139

**Comment by lolieatapple** [comment] 2023-03-14 02:20
so will the #139  support proxy?

**Comment by privatenumber** [comment] 2023-03-14 03:10
Yes, see the PR for details. If you're motivated, feel free to pick up the work. It should be done by the people that need it.

**Comment by lolieatapple** [comment] 2023-03-14 03:20
ok. thanks for PR. I couldn't wait any longer, so I've been using a modified version of axios on my local computer. :)

**Comment by privatenumber** [comment] 2023-03-14 03:33
If you like the project and use it, why not contribute back to it?

Fixing an Open Source issue you relate to is a great opportunity to make a positive impact on the community.

**Comment by lolieatapple** [comment] 2023-03-14 03:37
> 

haha, yes, you're right. but I like to use less code such as axios not like to write more code such as make http to support proxy. 

My principle is that the less code I write myself, the fewer bugs there are likely to be.

So this time I won't contribute any code, but maybe I'll have the opportunity to do so in the future. Nonetheless, thank you for creating such a great tool! 👍

**Comment by privatenumber** [comment] 2023-03-14 06:40
Sounds like an opportunity for you to learn more about writing scalable code with minimal footprint!

**Comment by privatenumber** [comment] 2023-03-16 03:57
Closing in favor of https://github.com/Nutlope/aicommits/issues/158 as it's a better documented request.
Also, this is not a bug, but a connection error as a result of a lack of feature.

**Closed by privatenumber** 2023-03-16 03:57 UTC
Labels: bug, pending triage
