### ISSUE TITLE
"\No newline at end of file" at start of generated commit message

### ISSUE THREAD

**Issue by crl-n** [Nutlope/aicommits#119] opened 2023-02-27 20:22 UTC
Hi. First of all, really cool project! 

Somehow this string ended up in the commit message:
<img width="708" alt="image" src="https://user-images.githubusercontent.com/65853349/221672869-9202b4e5-dfcd-4201-a5bb-f6b895331252.png">

Seems like it might be coming from the git diff output somehow, see here for some reference: https://thoughtbot.com/blog/no-newline-at-end-of-file

**Comment by privatenumber** [comment] 2023-03-02 05:46
Thanks for the report.

Since this is based on your specific changes and AI output, I'm thinking this is unreproducible. That said, I'm not sure how I can debug this...

Might have to just take note that this has happened and close it out until:
1. We somehow find a reproduction
2. Someone that's encountering it debugs it and opens a PR

**Comment by privatenumber** [comment] 2023-03-10 14:23
We're using the new model GPT model now, so hopefully this will no longer be an issue.

Closing for now, but feel free to comment/add reproduction and I'll re-open.

**Closed by privatenumber** 2023-03-10 14:23 UTC
Labels: bug, pending triage
